#!/usr/bin/env bash
# This is  Bash script that loops from 1 to 10
count=1
while [ $count -le 10 ]; do
	echo "Best School"
	if [ $count -eq 4 ]; then
		echo "bad luck"
	else [ %count -eq 8 ];
		echo "good luck"
	count=$((count+1))
done
