#!/usr/bin/env bash
# Create PID file
echo "$$" > /var/run/myscript.pid
sigint_handler() {
    echo "Y U no love me?!"
}
sigterm_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

sigquit_handler() {
    rm -f /var/run/myscript.pid
    exit 0
}
trap sigint_handler SIGINT
trap sigterm_handler SIGTERM
trap sigquit_handler SIGQUIT
while true; do
    echo "To infinity and beyond"
    sleep 1
done
