#!/usr/bin/env bash
# Last Task part 2
PIDFILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"
case "$1" in
    start)
        # Start the process in background
        $PROCESS &
        echo $! > "$PIDFILE"
        echo "manage_my_process started"
        ;;
    
    stop)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat "$PIDFILE")"
            rm -f "$PIDFILE"
            echo "manage_my_process stopped"
        fi
        ;;
    
    restart)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat "$PIDFILE")"
            rm -f "$PIDFILE"
        fi
        $PROCESS &
        echo $! > "$PIDFILE"
        echo "manage_my_process restarted"
        ;;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
