#!/usr/bin/env bash
# Comment on PID
#!/usr/bin/env bash
for pid in /proc/[0-9]*; do
    if [ -f "$pid/comm" ] && [[ $(cat "$pid/comm") == bash ]]; then
        echo "$(basename $pid) bash"
    fi
done

